coverage:
  status:
  # https://docs.codecov.com/docs/commit-status#
    patch:
      default:
        target: '80'
    project:
      default:
        target: auto
        threshold: 1
comment:
# https://docs.codecov.com/docs/pull-request-comments
  layout: "header" 
