name: Test and coverage

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v4
          with:
            go-version: 'stable'
        - name: Run coverage
          run: |
            go test -coverprofile=cov_grpc.txt google.golang.org/grpc/...
            cd "${GITHUB_WORKSPACE}"
            for MOD_FILE in $(find . -name 'go.mod' | grep -Ev '^\./go\.mod'); do
              pushd "$(dirname ${MOD_FILE})"
              go test -coverprofile=cov_${MOD_FILE}.txt ./...
              popd
            done
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v3
