name: Test and coverage

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v4
          with:
            go-version: 'stable'
        - name: Run coverage
          run: |
            mkdir coverage
            go test -coverprofile=./coverage/cov.out google.golang.org/grpc/...
            for MOD_FILE in $(find . -name 'go.mod' | grep -Ev '^\./go\.mod'); do
              echo ${GITHUB_WORKSPACE}
              go test -coverprofile=./coverage/cov_$(basename ${MOD_FILE}).out $(dirname ${MOD_FILE})/...
              # pushd "$(dirname ${MOD_FILE})"
              # go test -coverprofile=./coverage/cov_$(basename ${MOD_FILE}).out ./...
              # popd
            done
            # echo "mode: set" > coverage.out
            # for Dir in $(find ./* -maxdepth 10 -type d );
            # do
            #         if ls $Dir/*.go &> /dev/null;
            #         then
            #             go test -coverprofile=profile.out $Dir
            #             if [ -f profile.out ]
            #             then
            #                 cat profile.out | grep -v "mode: set" >> acc.out
            #             fi
            # fi
            # done
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v3
          with:
            directory: ./coverage/
